In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive/


In [0]:
# In following sections, the g-gap features are further processed to test CNN
c="/content/drive/My Drive/Colab Notebooks/allseq_ind.csv"
with open(c) as f:
    content = f.read() 
s=0
dat=content.split("\n") 
for i in dat:
    dat[s]=list(dat[s])
    s=s+1
          

    
import numpy as np
lm=1
tp=np.zeros(772)
for h in range(772):
    tp[h]=len(dat[lm])
    lm=lm+2
#%%
c="/content/drive/My Drive/Colab Notebooks/zero_ind.csv"
with open(c) as f:
    content0 = f.read() 
    
dat0=content0.split("\n") 
s=0
for i in range(len(dat0)):
    dat0[s]=dat0[s].split(",")
    s=s+1
    
   
import numpy as np
dataaa0=np.zeros((772,400))
ii=0; jj=0
for i in range(772):
    for j in range(400):
        dataaa0[i][j]=float(dat0[i][j])
        
tc=0
for i in range(772):
    tc=tp[i]-1
    dataaa0[i]=dataaa0[i]*tc
    
#%%
c="/content/drive/My Drive/Colab Notebooks/one_ind.csv"
with open(c) as f:
    content1 = f.read() 
    
dat1=content1.split("\n") 
s=0
for i in range(len(dat1)):
    dat1[s]=dat1[s].split(",")
    s=s+1
    
   
import numpy as np
dataaa1=np.zeros((772,400))
ii=0; jj=0
for i in range(772):
    for j in range(400):
        dataaa1[i][j]=float(dat1[i][j])
        
tc=0
for i in range(772):
    tc=tp[i]-1
    dataaa1[i]=dataaa1[i]*tc
    
#%%
c="/content/drive/My Drive/Colab Notebooks/two_ind.csv"
with open(c) as f:
    content2 = f.read() 
    
dat2=content2.split("\n") 
s=0
for i in range(len(dat2)):
    dat2[s]=dat2[s].split(",")
    s=s+1
    
   
import numpy as np
dataaa2=np.zeros((772,400))
ii=0; jj=0
for i in range(772):
    for j in range(400):
        dataaa2[i][j]=float(dat2[i][j])
        
tc=0
for i in range(772):
    tc=tp[i]-1
    dataaa2[i]=dataaa2[i]*tc
#%%
c="/content/drive/My Drive/Colab Notebooks/three_ind.csv"
with open(c) as f:
    content3 = f.read() 
    
dat3=content3.split("\n") 
s=0
for i in range(len(dat3)):
    dat3[s]=dat3[s].split(",")
    s=s+1
    
   
import numpy as np
dataaa3=np.zeros((772,400))
ii=0; jj=0
for i in range(772):
    for j in range(400):
        dataaa3[i][j]=float(dat3[i][j])
        
tc=0
for i in range(772):
    tc=tp[i]-1
    dataaa3[i]=dataaa3[i]*tc 

In [0]:
a = np.reshape(dataaa0,[772,20,20])
b = np.reshape(dataaa1,[772,20,20])
c = np.reshape(dataaa2,[772,20,20])
feature1=np.zeros((772,20,20,3))
for i in range(772):
  data = np.zeros( (20,20,3))
  data[:,:,0]=a[i,:,:]
  data[:,:,1]=b[i,:,:]
  data[:,:,2]=c[i,:,:]
  feature1[i]=data                
                  

In [0]:
a = np.reshape(dataaa0,[772,20,20])
b = np.reshape(dataaa1,[772,20,20])
c = np.reshape(dataaa3,[772,20,20])
feature2=np.zeros((772,20,20,3))
for i in range(772):
  data = np.zeros( (20,20,3))
  data[:,:,0]=a[i,:,:]
  data[:,:,1]=b[i,:,:]
  data[:,:,2]=c[i,:,:]
  feature2[i]=data 

In [0]:
a = np.reshape(dataaa0,[772,20,20])
b = np.reshape(dataaa2,[772,20,20])
c = np.reshape(dataaa3,[772,20,20])
feature3=np.zeros((772,20,20,3))
for i in range(772):
  data = np.zeros( (20,20,3))
  data[:,:,0]=a[i,:,:]
  data[:,:,1]=b[i,:,:]
  data[:,:,2]=c[i,:,:]
  feature3[i]=data                
                  

In [0]:
a = np.reshape(dataaa1,[772,20,20])
b = np.reshape(dataaa2,[772,20,20])
c = np.reshape(dataaa3,[772,20,20])
feature4=np.zeros((772,20,20,3))
for i in range(772):
  data = np.zeros( (20,20,3))
  data[:,:,0]=a[i,:,:]
  data[:,:,1]=b[i,:,:]
  data[:,:,2]=c[i,:,:]
  feature4[i]=data     

In [0]:
import numpy as np
label=np.zeros(772)
for i in range(386):
    label[i]=0
j=386  
for k in range(386):
    label[j]=1
    j=j+1

In [8]:
import os,cv2
import numpy as np
import matplotlib.pyplot as plt

from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

from keras import backend as K
K.set_image_data_format('channels_last')




from keras.utils import np_utils
from keras.models import Sequential
from keras.layers  import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.optimizers import SGD,RMSprop,adam# 
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import StratifiedKFold
import numpy
from keras.callbacks import ModelCheckpoint
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import ModelCheckpoint
import matplotlib.pyplot as plt
import numpy

Using TensorFlow backend.


In [9]:
filepath="/content/drive/My Drive/Colab Notebooks/new-weights-bench-cv10-0,1,22.hdf5" #.............................
model = Sequential()
model.add(Conv2D(32, (3, 3), border_mode='valid', input_shape=feature1[0].shape)) #............................
convout1 = Activation('relu')
model.add(convout1)
convout3 = Activation('relu')
model.add(convout3)
model.add(Conv2D(8,( 3, 3)))
  
model.add(MaxPooling2D(pool_size=(2,2 )))
model.add(Dropout(0.5))

model.add(Flatten())
model.add(Dense(170))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))

#model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
# load weights
model.load_weights(filepath)
# Compile model (required to make predictions)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
print("Created model and loaded weights from file")
# load pima indians dataset
p1=model.predict_classes(feature1) #................
#pre.apppend(t1)
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(label, p1)#...............................
print(cm1)
total1=sum(sum(cm1))
accuracy1=(cm1[0,0]+cm1[1,1])/total1
print(accuracy1)
scores = model.evaluate(feature1, label, verbose=0)#.............................
print(scores)






Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(20, 20, 3..., padding="valid")`
  This is separate from the ipykernel package so we can avoid doing imports until




Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Created model and loaded weights from file
[[290  96]
 [ 56 330]]
0.8031088082901554
[0.6216259994664727, 0.8031088082901554]


In [10]:
filepath="/content/drive/My Drive/Colab Notebooks/new-weights-bench-cv10-0,1,32.hdf5" #.............................
model = Sequential()
model.add(Conv2D(32, (3, 3), border_mode='valid', input_shape=feature2[0].shape)) #............................
convout1 = Activation('relu')
model.add(convout1)
convout3 = Activation('relu')
model.add(convout3)
model.add(Conv2D(8,( 3, 3)))
  
model.add(MaxPooling2D(pool_size=(2,2 )))
model.add(Dropout(0.5))

model.add(Flatten())
model.add(Dense(170))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))

#model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
# load weights
model.load_weights(filepath)
# Compile model (required to make predictions)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
print("Created model and loaded weights from file")
# load pima indians dataset
p2=model.predict_classes(feature2) #................
#pre.apppend(t1)
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(label, p2)#...............................
print(cm1)
total1=sum(sum(cm1))
accuracy1=(cm1[0,0]+cm1[1,1])/total1
print(accuracy1)
scores = model.evaluate(feature2, label, verbose=0)#.............................
print(scores)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(20, 20, 3..., padding="valid")`
  This is separate from the ipykernel package so we can avoid doing imports until


Created model and loaded weights from file
[[298  88]
 [ 55 331]]
0.8147668393782384
[0.7013261653096874, 0.8147668393782384]


In [11]:
filepath="/content/drive/My Drive/Colab Notebooks/new-weights-bench-cv10-0,2,32.hdf5" #.............................
model = Sequential()
model.add(Conv2D(32, (3, 3), border_mode='valid', input_shape=feature3[0].shape)) #............................
convout1 = Activation('relu')
model.add(convout1)
convout3 = Activation('relu')
model.add(convout3)
model.add(Conv2D(8,( 3, 3)))
  
model.add(MaxPooling2D(pool_size=(2,2 )))
model.add(Dropout(0.5))

model.add(Flatten())
model.add(Dense(170))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))

#model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
# load weights
model.load_weights(filepath)
# Compile model (required to make predictions)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
print("Created model and loaded weights from file")
# load pima indians dataset
p3=model.predict_classes(feature3) #................
#pre.apppend(t1)
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(label, p3)#...............................
print(cm1)
total1=sum(sum(cm1))
accuracy1=(cm1[0,0]+cm1[1,1])/total1
print(accuracy1)
scores = model.evaluate(feature3, label, verbose=0)#.............................
print(scores)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(20, 20, 3..., padding="valid")`
  This is separate from the ipykernel package so we can avoid doing imports until


Created model and loaded weights from file
[[309  77]
 [ 59 327]]
0.8238341968911918
[0.5960961967475056, 0.8238341968911918]


In [12]:
filepath="/content/drive/My Drive/Colab Notebooks/new-weights-bench-cv10-1,2,32.hdf5" #.............................
model = Sequential()
model.add(Conv2D(32, (3, 3), border_mode='valid', input_shape=feature4[0].shape)) #............................
convout1 = Activation('relu')
model.add(convout1)
convout3 = Activation('relu')
model.add(convout3)
model.add(Conv2D(8,( 3, 3)))
  
model.add(MaxPooling2D(pool_size=(2,2 )))
model.add(Dropout(0.5))

model.add(Flatten())
model.add(Dense(170))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))

#model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
# load weights
model.load_weights(filepath)
# Compile model (required to make predictions)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
print("Created model and loaded weights from file")
# load pima indians dataset
p4=model.predict_classes(feature4) #................
#pre.apppend(t1)
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(label, p4)#...............................
print(cm1)
total1=sum(sum(cm1))
accuracy1=(cm1[0,0]+cm1[1,1])/total1
print(accuracy1)
scores = model.evaluate(feature4, label, verbose=0)#.............................
print(scores)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(20, 20, 3..., padding="valid")`
  This is separate from the ipykernel package so we can avoid doing imports until


Created model and loaded weights from file
[[312  74]
 [ 50 336]]
0.8393782383419689
[0.5031714298294307, 0.8393782383419689]


In [0]:
featureee=np.zeros((772,4))
for i in range(772):
  featureee[i,0]=p1[i]
  featureee[i,1]=p2[i]
  featureee[i,2]=p3[i]
  featureee[i,3]=p4[i]
  

In [14]:
c="/content/drive/My Drive/Colab Notebooks/allseq_ind.csv"
with open(c) as f:
    content = f.read() 
s=0
dat=content.split("\n") 
for i in dat:
    dat[s]=list(dat[s])
    s=s+1
import numpy as np    
feature = np.zeros((772,20,))
print(feature)  
ppp=20
aa=0; rr=0; nn=0; dd=0; cc=0; qq=0; ee=0; gg=0; hh=0; ii=0; ll=0; kk=0; mm=0; ff=0; pp=0; ss=0; tt=0; ww=0; yy=0; vv=0; 
sss=0;
spsp=1;


for i in range(772):
    word = dat[spsp]
    v=0
    for l in word:
        if word[v]=='A':
            aa=aa+1
        elif word[v]=='R':
            rr=rr+1
        elif word[v]=='N':
            nn=nn+1
        elif word[v]=='D':
            dd=dd+1
        elif word[v]=='C':
            cc=cc+1
        elif word[v]=='Q':
            qq=qq+1
        elif word[v]=='E':
            ee=ee+1
        elif word[v]=='G':
            gg=gg+1
        elif word[v]=='H':
            hh=hh+1
        elif word[v]=='I':
            ii=ii+1
        elif word[v]=='L':
            ll=ll+1
        elif word[v]=='K':
            kk=kk+1
        elif word[v]=='M':
            mm=mm+1
        elif word[v]=='F':
            ff=ff+1
        elif word[v]=='P':
            pp=pp+1
        elif word[v]=='S':
            ss=ss+1
        elif word[v]=='T':
            tt=tt+1
        elif word[v]=='W':
            ww=ww+1
        elif word[v]=='Y':
            yy=yy+1
        else:
            vv=vv+1
        v=v+1    
    
    #aa=aa/20; rr=rr/20; nn=nn/20; dd=dd/20; cc=cc/20; qq=qq/20; ee=ee/20; gg=gg/20; hh=hh/20; ii=ii/20; ll=ll/20; kk=kk/20; mm=mm/20; ff=ff/20; pp=pp/20; ss=ss/20; tt=tt/20; ww=ww/20; yy=yy/20; vv=vv/20;
    feature[sss][0]=aa; feature[sss][1]=rr; feature[sss][2]=nn; feature[sss][3]=dd; feature[sss][4]=cc; feature[sss][5]=qq; feature[sss][6]=ee; feature[sss][7]=gg; feature[sss][8]=hh; feature[sss][9]=ii; feature[sss][10]=ll; feature[sss][11]=kk; feature[sss][12]=mm; feature[sss][13]=ff; feature[sss][14]=pp; feature[sss][15]=ss; feature[sss][16]=tt; feature[sss][17]=ww; feature[sss][18]=yy; feature[sss][19]=vv; 
    aa=0; rr=0; nn=0; dd=0; cc=0; qq=0; ee=0; gg=0; hh=0; ii=0; ll=0; kk=0; mm=0; ff=0; pp=0; ss=0; tt=0; ww=0; yy=0; vv=0;
    sss=sss+1
    spsp=spsp+2

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [0]:
inputt=np.zeros((772,24))
inputt[:,0:4]=featureee[:,:]
inputt[:,4:]=feature[:,:]

In [16]:
import pickle
filename='/content/drive/My Drive/Colab Notebooks/new-svm-benc10-4.sav'
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(inputt, label)
result1=loaded_model.predict(inputt)
print(result)

0.9002590673575129


In [17]:
cm1 = confusion_matrix(label, result1)
sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('Sensitivity : ', sensitivity1 )

specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Specificity : ', specificity1)
tp=cm1[0,0]
print('tp : ', tp)
fp=cm1[0,1]
print('fp : ', fp)
fn=cm1[1,0]
print('fn : ', fn)
tn=cm1[1,0]
print('tn : ', tn)
#%%
from sklearn.metrics import matthews_corrcoef
mcc = matthews_corrcoef(label,result1)
print('Matthews Correlation Coefficient:', mcc)

  #%%
total1=sum(sum(cm1))

accuracy1=(cm1[0,0]+cm1[1,1])/total1
print ('Accuracy : ', accuracy1)

import numpy as np
from sklearn import metrics
fpr, tpr, thresholds = metrics.roc_curve(label, result1)
aucc=metrics.auc(fpr, tpr)
print('AUC:', aucc)

Sensitivity :  0.9637305699481865
Specificity :  0.8367875647668394
tp :  372
fp :  14
fn :  63
tn :  63
Matthews Correlation Coefficient: 0.807047135736267
Accuracy :  0.9002590673575129
AUC: 0.9002590673575129
