# Run each cell one by one 

In [0]:
from google.colab import drive
drive.mount('/content/drive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive/


In [2]:
%cd /content/drive/My Drive/Colab Notebooks/

[Errno 2] No such file or directory: '/content/drive/My Drive/Colab Notebooks/'
/content


**Before running next cell, read the instruction**

In [0]:

#In the following code  tes3.txt is the file in which test peptides is
# Replace tes3.txt with any file which need to be predict.
# The file format must be .txt or .csv
# The test file must be in the folder in which all code files are
# test peptides must be in fasta format
# Test Peptides must be greater or equal to 5 length.
# Examples of fasta format file:

#    >peptide_0
#    AAAWWN
#    >peptide_1
#    ANAVRN

# where "peptide" word can be changed or anything else but "_" , and  ">" must same as it is and the number of example must be in ascending order (i.e. 0,1,2,3....) 



!python g-gap.py -g 0 -i tes3.txt -o DPC-Features-gap-0.csv
!python g-gap.py -g 1 -i tes3.txt -o DPC-Features-gap-1.csv
!python g-gap.py -g 2 -i tes3.txt -o DPC-Features-gap-2.csv
!python g-gap.py -g 3 -i tes3.txt -o DPC-Features-gap-3.csv

------Finished!------
------Finished!------
------Finished!------
------Finished!------


**Run all remaining cells without any changes**

In [0]:
c="/content/drive/My Drive/Colab Notebooks/tes3.txt"  #Folder path in drive where all sequences of test dataset is.
with open(c) as f:
    content = f.read() 
s=0
dat=content.split("\n") 
for i in dat:
    dat[s]=list(dat[s])
    s=s+1

dd=len(dat)
ddd=dd/2
dddd=int(ddd)
import numpy as np
lm=1
tp=np.zeros(dddd)
for h in range(dddd):
    tp[h]=len(dat[lm])
    lm=lm+2
#%%
c="/content/drive/My Drive/Colab Notebooks/DPC-Features-gap-0.csv"  #Folder path in drive where all g-gap DPC features with gap 0 is.
with open(c) as f:
    content0 = f.read() 
    
dat0=content0.split("\n") 
s=1
for i in range(len(dat0)-1):
    dat0[s]=dat0[s].split(",")
    s=s+1

newdat0=dat0[1:]
import numpy as np
dataaa0=np.zeros((dddd,401))
ii=0; jj=0
for i in range(dddd):
    for j in range(401):
        dataaa0[i][j]=float(newdat0[i][j])
        
newdataaa0=np.zeros((dddd,400))
for i in range(dddd):
    newdataaa0[i][:]=dataaa0[i][1:401]
    
tc=0
for i in range(dddd):
    tc=tp[i]-1
    newdataaa0[i]=newdataaa0[i]*tc 
#%%
c="/content/drive/My Drive/Colab Notebooks/DPC-Features-gap-1.csv"  #Folder path in drive where all g-gap DPC features with gap 1 is.
with open(c) as f:
    content1 = f.read() 
    
dat1=content1.split("\n") 
s=1
for i in range(len(dat1)-1):
    dat1[s]=dat1[s].split(",")
    s=s+1

newdat1=dat1[1:]
import numpy as np
dataaa1=np.zeros((dddd,401))
ii=0; jj=0
for i in range(dddd):
    for j in range(401):
        dataaa1[i][j]=float(newdat1[i][j])
        
newdataaa1=np.zeros((dddd,400))
for i in range(dddd):
    newdataaa1[i][:]=dataaa1[i][1:401]
    
tc=0
for i in range(dddd):
    tc=tp[i]-1
    newdataaa1[i]=newdataaa1[i]*tc
    
#%%
c="/content/drive/My Drive/Colab Notebooks/DPC-Features-gap-2.csv"  #Folder path in drive where all g-gap DPC features with gap 2 is.
with open(c) as f:
    content2 = f.read() 
    
dat2=content2.split("\n") 
s=1
for i in range(len(dat2)-1):
    dat2[s]=dat2[s].split(",")
    s=s+1

newdat2=dat2[1:]
import numpy as np
dataaa2=np.zeros((dddd,401))
ii=0; jj=0
for i in range(dddd):
    for j in range(401):
        dataaa2[i][j]=float(newdat2[i][j])
        
newdataaa2=np.zeros((dddd,400))
for i in range(dddd):
    newdataaa2[i][:]=dataaa2[i][1:401]
    
tc=0
for i in range(dddd):
    tc=tp[i]-1
    newdataaa2[i]=newdataaa2[i]*tc
    
#%%
c="/content/drive/My Drive/Colab Notebooks/DPC-Features-gap-3.csv"  #Folder path in drive where all g-gap DPC features with gap 3 is.
with open(c) as f:
    content3 = f.read() 
    
dat3=content3.split("\n") 
s=1
for i in range(len(dat3)-1):
    dat3[s]=dat3[s].split(",")
    s=s+1

newdat3=dat3[1:]
import numpy as np
dataaa3=np.zeros((dddd,401))
ii=0; jj=0
for i in range(dddd):
    for j in range(401):
        dataaa3[i][j]=float(newdat3[i][j])
        
newdataaa3=np.zeros((dddd,400))
for i in range(dddd):
    newdataaa3[i][:]=dataaa3[i][1:401]
    
tc=0
for i in range(dddd):
    tc=tp[i]-1
    newdataaa3[i]=newdataaa3[i]*tc
#%%
 

In [0]:
#Images for DPC features with gap 0,1,2
a = np.reshape(newdataaa0,[dddd,20,20])
b = np.reshape(newdataaa1,[dddd,20,20])
c = np.reshape(newdataaa2,[dddd,20,20])
feature1=np.zeros((dddd,20,20,3))
for i in range(dddd):
  data = np.zeros( (20,20,3))
  data[:,:,0]=a[i,:,:]
  data[:,:,1]=b[i,:,:]
  data[:,:,2]=c[i,:,:]
  feature1[i]=data     

In [0]:
#Images for DPC features with gap 0,1,3
a = np.reshape(newdataaa0,[dddd,20,20])
b = np.reshape(newdataaa1,[dddd,20,20])
c = np.reshape(newdataaa3,[dddd,20,20])
feature2=np.zeros((dddd,20,20,3))
for i in range(dddd):
  data = np.zeros( (20,20,3))
  data[:,:,0]=a[i,:,:]
  data[:,:,1]=b[i,:,:]
  data[:,:,2]=c[i,:,:]
  feature2[i]=data 

In [0]:
#Images for DPC features with gap 0,2,3
a = np.reshape(newdataaa0,[dddd,20,20])
b = np.reshape(newdataaa2,[dddd,20,20])
c = np.reshape(newdataaa3,[dddd,20,20])
feature3=np.zeros((dddd,20,20,3))
for i in range(dddd):
  data = np.zeros( (20,20,3))
  data[:,:,0]=a[i,:,:]
  data[:,:,1]=b[i,:,:]
  data[:,:,2]=c[i,:,:]
  feature3[i]=data 

In [0]:
#Images for DPC features with gap 1,2,3
a = np.reshape(newdataaa1,[dddd,20,20])
b = np.reshape(newdataaa2,[dddd,20,20])
c = np.reshape(newdataaa3,[dddd,20,20])
feature4=np.zeros((dddd,20,20,3))
for i in range(dddd):
  data = np.zeros( (20,20,3))
  data[:,:,0]=a[i,:,:]
  data[:,:,1]=b[i,:,:]
  data[:,:,2]=c[i,:,:]
  feature4[i]=data

In [0]:
import os,cv2
import numpy as np
import matplotlib.pyplot as plt

from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

from keras import backend as K
K.set_image_data_format('channels_last')




from keras.utils import np_utils
from keras.models import Sequential
from keras.layers  import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.optimizers import SGD,RMSprop,adam# 
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import StratifiedKFold
import numpy
from keras.callbacks import ModelCheckpoint
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import ModelCheckpoint
import matplotlib.pyplot as plt
import numpy

Using TensorFlow backend.


In [0]:
filepath="/content/drive/My Drive/Colab Notebooks/new-weights-bench-cv10-0,1,22.hdf5" #.............................
model = Sequential()
model.add(Conv2D(32, (3, 3), border_mode='valid', input_shape=feature1[0].shape)) #............................
convout1 = Activation('relu')
model.add(convout1)
convout3 = Activation('relu')
model.add(convout3)
model.add(Conv2D(8,( 3, 3)))
  
model.add(MaxPooling2D(pool_size=(2,2 )))
model.add(Dropout(0.5))

model.add(Flatten())
model.add(Dense(170))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))

#model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
# load weights
model.load_weights(filepath)
# Compile model (required to make predictions)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
print("Created model and loaded weights from file")

p1=model.predict_classes(feature1) #................


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(20, 20, 3..., padding="valid")`
  This is separate from the ipykernel package so we can avoid doing imports until


Created model and loaded weights from file


In [0]:
filepath="/content/drive/My Drive/Colab Notebooks/new-weights-bench-cv10-0,1,32.hdf5" #.............................
model = Sequential()
model.add(Conv2D(32, (3, 3), border_mode='valid', input_shape=feature2[0].shape)) #............................
convout1 = Activation('relu')
model.add(convout1)
convout3 = Activation('relu')
model.add(convout3)
model.add(Conv2D(8,( 3, 3)))
  
model.add(MaxPooling2D(pool_size=(2,2 )))
model.add(Dropout(0.5))

model.add(Flatten())
model.add(Dense(170))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))

#model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
# load weights
model.load_weights(filepath)
# Compile model (required to make predictions)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
print("Created model and loaded weights from file")

p2=model.predict_classes(feature2) #................

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(20, 20, 3..., padding="valid")`
  This is separate from the ipykernel package so we can avoid doing imports until


Created model and loaded weights from file


In [0]:
filepath="/content/drive/My Drive/Colab Notebooks/new-weights-bench-cv10-0,2,32.hdf5" #.............................
model = Sequential()
model.add(Conv2D(32, (3, 3), border_mode='valid', input_shape=feature3[0].shape)) #............................
convout1 = Activation('relu')
model.add(convout1)
convout3 = Activation('relu')
model.add(convout3)
model.add(Conv2D(8,( 3, 3)))
  
model.add(MaxPooling2D(pool_size=(2,2 )))
model.add(Dropout(0.5))

model.add(Flatten())
model.add(Dense(170))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))

#model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
# load weights
model.load_weights(filepath)
# Compile model (required to make predictions)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
print("Created model and loaded weights from file")

p3=model.predict_classes(feature3) #................

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(20, 20, 3..., padding="valid")`
  This is separate from the ipykernel package so we can avoid doing imports until


Created model and loaded weights from file


In [0]:
filepath="/content/drive/My Drive/Colab Notebooks/new-weights-bench-cv10-1,2,32.hdf5" #.............................
model = Sequential()
model.add(Conv2D(32, (3, 3), border_mode='valid', input_shape=feature4[0].shape)) #............................
convout1 = Activation('relu')
model.add(convout1)
convout3 = Activation('relu')
model.add(convout3)
model.add(Conv2D(8,( 3, 3)))
  
model.add(MaxPooling2D(pool_size=(2,2 )))
model.add(Dropout(0.5))

model.add(Flatten())
model.add(Dense(170))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))

#model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
# load weights
model.load_weights(filepath)
# Compile model (required to make predictions)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=["accuracy"])
print("Created model and loaded weights from file")

p4=model.predict_classes(feature4) #................

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(20, 20, 3..., padding="valid")`
  This is separate from the ipykernel package so we can avoid doing imports until


Created model and loaded weights from file


In [0]:
featureee=np.zeros((dddd,4))
for i in range(dddd):
  featureee[i,0]=p1[i]
  featureee[i,1]=p2[i]
  featureee[i,2]=p3[i]
  featureee[i,3]=p4[i]

In [0]:
c="/content/drive/My Drive/Colab Notebooks/tes3.txt"
with open(c) as f:
    content = f.read() 
s=0
dat=content.split("\n") 
for i in dat:
    dat[s]=list(dat[s])
    s=s+1
import numpy as np    
feature = np.zeros((dddd,20,))
print(feature)  
ppp=20
aa=0; rr=0; nn=0; dd=0; cc=0; qq=0; ee=0; gg=0; hh=0; ii=0; ll=0; kk=0; mm=0; ff=0; pp=0; ss=0; tt=0; ww=0; yy=0; vv=0; 
sss=0;
spsp=1;


for i in range(dddd):
    word = dat[spsp]
    v=0
    for l in word:
        if word[v]=='A':
            aa=aa+1
        elif word[v]=='R':
            rr=rr+1
        elif word[v]=='N':
            nn=nn+1
        elif word[v]=='D':
            dd=dd+1
        elif word[v]=='C':
            cc=cc+1
        elif word[v]=='Q':
            qq=qq+1
        elif word[v]=='E':
            ee=ee+1
        elif word[v]=='G':
            gg=gg+1
        elif word[v]=='H':
            hh=hh+1
        elif word[v]=='I':
            ii=ii+1
        elif word[v]=='L':
            ll=ll+1
        elif word[v]=='K':
            kk=kk+1
        elif word[v]=='M':
            mm=mm+1
        elif word[v]=='F':
            ff=ff+1
        elif word[v]=='P':
            pp=pp+1
        elif word[v]=='S':
            ss=ss+1
        elif word[v]=='T':
            tt=tt+1
        elif word[v]=='W':
            ww=ww+1
        elif word[v]=='Y':
            yy=yy+1
        else:
            vv=vv+1
        v=v+1    
    
    #aa=aa/20; rr=rr/20; nn=nn/20; dd=dd/20; cc=cc/20; qq=qq/20; ee=ee/20; gg=gg/20; hh=hh/20; ii=ii/20; ll=ll/20; kk=kk/20; mm=mm/20; ff=ff/20; pp=pp/20; ss=ss/20; tt=tt/20; ww=ww/20; yy=yy/20; vv=vv/20;
    feature[sss][0]=aa; feature[sss][1]=rr; feature[sss][2]=nn; feature[sss][3]=dd; feature[sss][4]=cc; feature[sss][5]=qq; feature[sss][6]=ee; feature[sss][7]=gg; feature[sss][8]=hh; feature[sss][9]=ii; feature[sss][10]=ll; feature[sss][11]=kk; feature[sss][12]=mm; feature[sss][13]=ff; feature[sss][14]=pp; feature[sss][15]=ss; feature[sss][16]=tt; feature[sss][17]=ww; feature[sss][18]=yy; feature[sss][19]=vv; 
    aa=0; rr=0; nn=0; dd=0; cc=0; qq=0; ee=0; gg=0; hh=0; ii=0; ll=0; kk=0; mm=0; ff=0; pp=0; ss=0; tt=0; ww=0; yy=0; vv=0;
    sss=sss+1
    spsp=spsp+2

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [0]:
inputt=np.zeros((dddd,24))
inputt[:,0:4]=featureee[:,:]
inputt[:,4:]=feature[:,:]

In [0]:
from sklearn.svm import SVC  
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm
from sklearn.svm import SVC  
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm  
from sklearn.metrics import classification_report, confusion_matrix
import pickle

In [0]:
import pickle
filename='/content/drive/My Drive/Colab Notebooks/new-svm-benc10-4.sav'
loaded_model = pickle.load(open(filename, 'rb'))
result1=loaded_model.predict(inputt)
print(result1)

[0. 0. 0.]
